---
- name: Set macOS defaults
  include_role:
    name: feffi.macos-defaults
  vars:
    macos_defaults:
      defaults:
        - { domain: "com.apple.SoftwareUpdate", key: "ScheduleFrequency", type: "integer", value: "{{ macos_softwareupdate.frequency }}", description: "Software Update Check Interval set to x days" }
        - { domain: "com.apple.appstore", key: "ShowDebugMenu", type: "boolean", value: "{{ macos_softwareupdate.debug }}", description: "Show debug menu in AppStore" }
        - { domain: "com.apple.appstore", key: "WebKitDeveloperExtras", type: "boolean", value: "{{ macos_softwareupdate.webkit }}", description: "Set the Develop menu and the Web Inspector in AppStore" }

- name: Determine if softwareupdate should install updates
  set_fact:
    macos_softwareupdate_action: "--install"
  when: macos_softwareupdate.install

- name: Determine if softwareupdate should only download updates
  set_fact:
    macos_softwareupdate_action: "--download"
  when: not macos_softwareupdate.install

- name: Determine if softwareupdate should install recommended updates only
  set_fact:
    macos_softwareupdate_updates: "--recommended"
  when: macos_softwareupdate.recommended

- name: Determine if softwareupdate should install all updates
  set_fact:
    macos_softwareupdate_updates: "--all"
  when: not macos_softwareupdate.recommended

- name: Run assembled command
  command: "{{ 'softwareupdate ' + macos_softwareupdate_action + ' ' + macos_softwareupdate_updates }}"
  register: softwareupdate_assembled
  changed_when: "softwareupdate_assembled.rc != 0 and 'No updates are available.' not in softwareupdate_assembled.stderr"
